In [10]:
# Dependencies
import pandas as pd

In [11]:
# List of file names to be combined 
files21 = ['citbike\JC-202101-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df21_list = []

# Loop through each file in the list
for file in files21:
    # Read the file into a dataframe
    df21 = pd.read_csv(file)

    # Append the dataframe to the list
    df21_list.append(df21)

# Concatenate all dataframes in the list into one dataframe
df21 = pd.concat(df21_list)

# Show dataframe
df21

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1

In [12]:
# List of file names to be combined 
files22 = ['citbike\JC-202102-citibike-tripdata.csv']

# Create an empty list to store each dataframe
df22_list = []

# Loop through each file in the list
for f in files22:
    # Read the file into a dataframe
    df22 = pd.read_csv(f)

    # Append the dataframe to the list
    df22_list.append(df22)

# Concatenate all dataframes in the list into one DataFrame
df22 = pd.concat(df22_list)

# Show dataframe
df22

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,3F8FD9A051C0E3DA,docked_bike,2021-02-24 18:05:45,2021-02-24 18:12:27,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4877,B91F3593C0C06D04,docked_bike,2021-02-22 18:22:04,2021-02-22 18:28:45,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4878,A790954A017D07CB,docked_bike,2021-02-13 12:21:49,2021-02-13 12:27:51,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4879,42B1932D06CEE034,docked_bike,2021-02-25 11:20:29,2021-02-25 11:25:23,Columbus Drive,JC014,Morris Canal,JC072,40.718355,-74.038914,40.712419,-74.038526,member
4880,F71732ECE7CD02CF,docked_bike,2021-02-19 13:59:22,2021-02-19 14:05:47,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member

In [13]:
# Concatenate all dataframes for all the years into one
combined_df = pd.concat([df21, df22,], axis=0)

# Display the results
combined_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,266.0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273.0,Manila & 1st,40.721651,-74.042884,3209.0,Brunswick St,40.724176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1543.0,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681.0,Grand St,40.715178,-74.037683,3213.0,Van Vorst Park,40.718489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1461.0,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681.0,Grand St,40.715178,-74.037683,3213.0,Van Vorst Park,40.718489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,793.0,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185.0,City Hall,40.717732,-74.043845,3199.0,Newport Pkwy,40.728745,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,596.0,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639.0,Harborside,40.719252,-74.034234,3209.0,Brunswick St,40.724176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-24 18:12:27,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-22 18:28:45,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-13 12:27:51,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-25 11:25:23,Columbus Drive,JC014,Morris Canal,JC072,40.718355,-74.038914,40.712419,-74.038526,member
4880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-19 14:05:47,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member

In [14]:
# Dictionary mapping values in the 'gender' column to new values
mapping = {0: 'Unknown', 1: 'Male', 2: 'Female'}

# Use the 'map' method to change the values in the 'gender' column
combined_df['gender'] = combined_df['gender'].map(mapping)

# Show DataFrame
combined_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,266.0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273.0,Manila & 1st,40.721651,-74.042884,3209.0,Brunswick St,40.724176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1543.0,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681.0,Grand St,40.715178,-74.037683,3213.0,Van Vorst Park,40.718489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1461.0,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681.0,Grand St,40.715178,-74.037683,3213.0,Van Vorst Park,40.718489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,793.0,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185.0,City Hall,40.717732,-74.043845,3199.0,Newport Pkwy,40.728745,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,596.0,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639.0,Harborside,40.719252,-74.034234,3209.0,Brunswick St,40.724176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-24 18:12:27,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-22 18:28:45,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-13 12:27:51,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-25 11:25:23,Columbus Drive,JC014,Morris Canal,JC072,40.718355,-74.038914,40.712419,-74.038526,member
4880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-02-19 14:05:47,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member

In [ ]:
# Save the dataframe to a CSV file
combined_df.to_csv('datecitibike.csv', index=False)